from contextlib import asynccontextmanager

import uvicorn
from fastapi import FastAPI

from config import settings
from db import init_db


@asynccontextmanager
async def lifespan(_: FastAPI):
    init_db()
    yield


app = FastAPI(lifespan=lifespan)


@app.get("/")
def read_root():
    return {"message": "Hello, world!", "db_path": str(settings.db_path)}
from fastapi import Request

@app.get("/health/db")
def db_health():
    return {"ok": settings.db_path.exists(), "db_path": str(settings.db_path)}

# Ingestion endpoint
from fastapi import UploadFile, File

from db import get_db_connection
import hashlib
import time
from pathlib import Path
import io
import os
from PyPDF2 import PdfReader

from fastapi import Form

from fastapi import Body
from fastapi.responses import JSONResponse
import json

from store import ingest_pdf_bytes
from pipeline.runner import process_document
from pipeline.persist import load_document_bundle, document_counts


@app.post("/companies")
async def add_company(
    name: str = Form(...),
    ticker: str = Form(None),
    exchange: str = Form(None),
    sector: str = Form(None),
    industry: str = Form(None),
    isin: str = Form(None)
):
    """
    Add a new company to the database (v3 schema).

    All fields except 'name' are optional. 'isin' must be unique if provided.
    """
    db = get_db_connection()
    try:
        cur = db.cursor()
        cur.execute("""
            INSERT INTO companies (
                id, name, ticker, exchange, sector, industry, isin
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            # id will be autogenerated as a UUID or similar if handled upstream, else can use name as pk for now
            hashlib.sha256(f"{name}-{time.time()}".encode()).hexdigest(),
            name,
            ticker,
            exchange,
            sector,
            industry,
            isin,
        ))
        db.commit()
        company_id = cur.lastrowid
        return JSONResponse({"success": True, "id": company_id})
    except Exception as e:
        return JSONResponse({"success": False, "error": str(e)}, status_code=400)
    finally:
        db.close()

@app.post("/events")
async def add_event(
    company_id: str = Form(...),
    event_type: str = Form(...),
    event_date: str = Form(...),
    fiscal_year: int = Form(None),
    fiscal_quarter: int = Form(None),
    title: str = Form(None),
    source_url: str = Form(None),
    document_id: str = Form(None),
    status: str = Form("processed")
):
    """
    Add a new event to the database (v3 schema).

    'company_id', 'event_type', and 'event_date' are required fields.
    Others are optional.
    """
    db = get_db_connection()
    try:
        cur = db.cursor()
        import hashlib, time, uuid  # import inside function to avoid issues at top of file
        event_id = hashlib.sha256(f"{company_id}-{event_type}-{event_date}-{time.time()}".encode()).hexdigest()
        cur.execute("""
            INSERT INTO events (
                id, company_id, event_type, event_date, fiscal_year, fiscal_quarter, title, source_url, document_id, status
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            event_id,
            company_id,
            event_type,
            event_date,
            fiscal_year,
            fiscal_quarter,
            title,
            source_url,
            document_id,
            status,
        ))
        db.commit()
        return JSONResponse({"success": True, "id": event_id})
    except Exception as e:
        return JSONResponse({"success": False, "error": str(e)}, status_code=400)
    finally:
        db.close()

@app.post("/ingest-pdf")
async def ingest_pdf(
    file: UploadFile = File(...),
    company_id: str = Form(None),
    source_url: str = Form(None),
    title: str = Form(None),
    document_kind: str = Form(None),
):
    """
    Ingest a PDF file: store on disk and optionally record metadata in documents.
    """
    try:
        if file.content_type != "application/pdf":
            return JSONResponse({"success": False, "error": "Uploaded file is not a PDF."}, status_code=400)
        contents = await file.read()
        result = ingest_pdf_bytes(
            contents,
            company_id=company_id,
            source_url=source_url,
            title=title or file.filename,
            document_kind=document_kind,
        )
        return JSONResponse({"success": True, **result})
    except Exception as e:
        return JSONResponse({"success": False, "error": str(e)}, status_code=400)


@app.get("/documents/{document_id}")
def get_document(document_id: str):
    db = get_db_connection()
    try:
        bundle = load_document_bundle(db, document_id)
        if not bundle:
            return JSONResponse({"success": False, "error": "not found"}, status_code=404)
        counts = document_counts(db, document_id)
        return JSONResponse({"success": True, **bundle, "counts": counts})
    finally:
        db.close()


@app.post("/documents/{document_id}/process")
def process_document_endpoint(document_id: str, force: bool = False):
    result = process_document(document_id, force=force)
    status = 200 if result.get("success") else 400
    return JSONResponse({"success": result.get("success", False), **result}, status_code=status)




if __name__ == "__main__":
    uvicorn.run("main:app", host="127.0.0.1", port=8001, reload=True)